package de.taymaerz.skyfox.common.theming

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object AplColorsBlue {

    // region Light Default
    val lightDefault = lightColorScheme(
        primary = Color(0xFF2D638E),
        onPrimary = Color(0xFFF6F9FF),
        primaryContainer = Color(0xFF91C3F4),
        onPrimaryContainer = Color(0xFF003E63),
        secondary = Color(0xFF4F6173),
        onSecondary = Color(0xFFF6F9FF),
        secondaryContainer = Color(0xFFD2E4FA),
        onSecondaryContainer = Color(0xFF425365),
        tertiary = Color(0xFF89521A),
        onTertiary = Color(0xFFFFF7F4),
        tertiaryContainer = Color(0xFFFDB473),
        onTertiaryContainer = Color(0xFF603300),
        error = Color(0xFFBB1B1B),
        onError = Color(0xFFFFF7F6),
        errorContainer = Color(0xFFFE4E44),
        onErrorContainer = Color(0xFF570003),
        background = Color(0xFFF9F9FD),
        onBackground = Color(0xFF303336),
        surface = Color(0xFFF9F9FD),
        onSurface = Color(0xFF303336),
        surfaceVariant = Color(0xFFE1E2E6),
        onSurfaceVariant = Color(0xFF5D5F63),
        outline = Color(0xFF797B7E),
        outlineVariant = Color(0xFFB1B2B6),
        inverseSurface = Color(0xFF0C0E11),
        inverseOnSurface = Color(0xFF9B9DA1),
        inversePrimary = Color(0xFF91C3F4),
        surfaceDim = Color(0xFFD9DADE),
        surfaceBright = Color(0xFFF9F9FD),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF3F3F7),
        surfaceContainer = Color(0xFFEDEEF2),
        surfaceContainerHigh = Color(0xFFE7E8EC),
        surfaceContainerHighest = Color(0xFFE1E2E6),
    )
    // endregion

    // region Light Medium Contrast
    val lightMediumContrast = lightColorScheme(
        primary = Color(0xFF004670),
        onPrimary = Color(0xFFBDDDFF),
        primaryContainer = Color(0xFF4579A5),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF334556),
        onSecondary = Color(0xFFC9DCF1),
        secondaryContainer = Color(0xFF64768A),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF663700),
        onTertiary = Color(0xFFFFD1AB),
        tertiaryContainer = Color(0xFFA2672E),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF8C0009),
        onError = Color(0xFFFFCEC8),
        errorContainer = Color(0xFFDA342E),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFF9F9FD),
        onBackground = Color(0xFF222427),
        surface = Color(0xFFF9F9FD),
        onSurface = Color(0xFF222427),
        surfaceVariant = Color(0xFFE1E2E6),
        onSurfaceVariant = Color(0xFF414346),
        outline = Color(0xFF5D5F63),
        outlineVariant = Color(0xFF797B7E),
        inverseSurface = Color(0xFF0C0E11),
        inverseOnSurface = Color(0xFFC3C5C8),
        inversePrimary = Color(0xFF91C3F4),
        surfaceDim = Color(0xFFD9DADE),
        surfaceBright = Color(0xFFF9F9FD),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF3F3F7),
        surfaceContainer = Color(0xFFEDEEF2),
        surfaceContainerHigh = Color(0xFFE7E8EC),
        surfaceContainerHighest = Color(0xFFE1E2E6),
    )
    // endregion

    // region Light High Contrast
    val lightHighContrast = lightColorScheme(
        primary = Color(0xFF00263F),
        onPrimary = Color(0xFFBEDEFF),
        primaryContainer = Color(0xFF2D638E),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF132536),
        onSecondary = Color(0xFFC9DCF2),
        secondaryContainer = Color(0xFF4F6173),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF3A1D00),
        onTertiary = Color(0xFFFFD1AC),
        tertiaryContainer = Color(0xFF89521A),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFF510003),
        onError = Color(0xFFFFCFC9),
        errorContainer = Color(0xFFBB1B1B),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFFF9F9FD),
        onBackground = Color(0xFF000000),
        surface = Color(0xFFF9F9FD),
        onSurface = Color(0xFF000000),
        surfaceVariant = Color(0xFFE1E2E6),
        onSurfaceVariant = Color(0xFF222427),
        outline = Color(0xFF414346),
        outlineVariant = Color(0xFF5D5F63),
        inverseSurface = Color(0xFF0C0E11),
        inverseOnSurface = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFF97CAFA),
        surfaceDim = Color(0xFFD9DADE),
        surfaceBright = Color(0xFFF9F9FD),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF3F3F7),
        surfaceContainer = Color(0xFFEDEEF2),
        surfaceContainerHigh = Color(0xFFE7E8EC),
        surfaceContainerHighest = Color(0xFFE1E2E6),
    )
    // endregion

    // region Dark Default
    val darkDefault = darkColorScheme(
        primary = Color(0xFF91C3F4),
        onPrimary = Color(0xFF003E63),
        primaryContainer = Color(0xFF73A5D4),
        onPrimaryContainer = Color(0xFF00253E),
        secondary = Color(0xFFB6C8DE),
        onSecondary = Color(0xFF304253),
        secondaryContainer = Color(0xFF2B3D4E),
        onSecondaryContainer = Color(0xFFAFC1D6),
        tertiary = Color(0xFFFFC697),
        onTertiary = Color(0xFF6C3B02),
        tertiaryContainer = Color(0xFFFDB473),
        onTertiaryContainer = Color(0xFF603300),
        error = Color(0xFFFF7164),
        onError = Color(0xFF4A0002),
        errorContainer = Color(0xFFAC0C12),
        onErrorContainer = Color(0xFFFFB8B0),
        background = Color(0xFF0C0E11),
        onBackground = Color(0xFFE4E5E9),
        surface = Color(0xFF0C0E11),
        onSurface = Color(0xFFE4E5E9),
        surfaceVariant = Color(0xFF242629),
        onSurfaceVariant = Color(0xFF929397),
        outline = Color(0xFF747579),
        outlineVariant = Color(0xFF46484B),
        inverseSurface = Color(0xFFF9F9FD),
        inverseOnSurface = Color(0xFF535559),
        inversePrimary = Color(0xFF2D638E),
        surfaceDim = Color(0xFF0C0E11),
        surfaceBright = Color(0xFF2A2C2F),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF111416),
        surfaceContainer = Color(0xFF171A1D),
        surfaceContainerHigh = Color(0xFF1D2023),
        surfaceContainerHighest = Color(0xFF242629),
    )
    // endregion

    // region Dark Medium Contrast
    val darkMediumContrast = darkColorScheme(
        primary = Color(0xFF91C3F4),
        onPrimary = Color(0xFF003353),
        primaryContainer = Color(0xFF73A5D4),
        onPrimaryContainer = Color(0xFF001627),
        secondary = Color(0xFFB6C8DE),
        onSecondary = Color(0xFF263849),
        secondaryContainer = Color(0xFF64768A),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFFFFC697),
        onTertiary = Color(0xFF5F3200),
        tertiaryContainer = Color(0xFFFDB473),
        onTertiaryContainer = Color(0xFF512A00),
        error = Color(0xFFFF9F94),
        onError = Color(0xFF600004),
        errorContainer = Color(0xFFDA342E),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0xFF0C0E11),
        onBackground = Color(0xFFFFFFFF),
        surface = Color(0xFF0C0E11),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF242629),
        onSurfaceVariant = Color(0xFFB7B9BC),
        outline = Color(0xFF929397),
        outlineVariant = Color(0xFF747579),
        inverseSurface = Color(0xFFF9F9FD),
        inverseOnSurface = Color(0xFF36383C),
        inversePrimary = Color(0xFF205984),
        surfaceDim = Color(0xFF0C0E11),
        surfaceBright = Color(0xFF2A2C2F),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF111416),
        surfaceContainer = Color(0xFF171A1D),
        surfaceContainerHigh = Color(0xFF1D2023),
        surfaceContainerHighest = Color(0xFF242629),
    )
    // endregion

    // region Dark High Contrast
    val darkHighContrast = darkColorScheme(
        primary = Color(0xFFD3E8FF),
        onPrimary = Color(0xFF002E4C),
        primaryContainer = Color(0xFF73A5D4),
        onPrimaryContainer = Color(0xFF000000),
        secondary = Color(0xFFD5E7FD),
        onSecondary = Color(0xFF1C2E3E),
        secondaryContainer = Color(0xFF8DA0B4),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFFFFE0C8),
        onTertiary = Color(0xFF452300),
        tertiaryContainer = Color(0xFFFDB473),
        onTertiaryContainer = Color(0xFF190900),
        error = Color(0xFFFFDEDA),
        onError = Color(0xFF600004),
        errorContainer = Color(0xFFFF7164),
        onErrorContainer = Color(0xFF000000),
        background = Color(0xFF0C0E11),
        onBackground = Color(0xFFFFFFFF),
        surface = Color(0xFF0C0E11),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF242629),
        onSurfaceVariant = Color(0xFFE4E5E9),
        outline = Color(0xFFB7B9BC),
        outlineVariant = Color(0xFF929397),
        inverseSurface = Color(0xFFF9F9FD),
        inverseOnSurface = Color(0xFF000000),
        inversePrimary = Color(0xFF003B5F),
        surfaceDim = Color(0xFF0C0E11),
        surfaceBright = Color(0xFF2A2C2F),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF111416),
        surfaceContainer = Color(0xFF171A1D),
        surfaceContainerHigh = Color(0xFF1D2023),
        surfaceContainerHighest = Color(0xFF242629),
    )
    // endregion
}
